# Archivo: config.py - MANTENIENDO 10 SEGUNDOS
API_KEY = "F9D9iYQqpiQvZ7FqSuaGugeN1I4QfnBTMnro1SGrga84PZeC7SpXFHiwqkWBkGlo"
API_SECRET = "yAseWTGu6vFlPKyIGkhttip23lcLVsvnybOgflFSt23EE1RjVg0mzdtTE84DBVNY"
TRADING_ENABLED = True
SYMBOLS = ["BNBUSDC", "FETUSDC", "SOLUSDC", "LINKUSDC", "XLMUSDC"]
TIMEFRAMES = {"30m": "30m", "1h": "1h", "2h": "2h"}
TIMEFRAME_WEIGHTS = {"30m": 0.30, "1h": 0.30, "2h": 0.40}
UPDATE_INTERVAL = 10  # ✅ MANTENIENDO TUS 10 SEGUNDOS
MIN_TRADE_DIFF = 1.0